config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :notes
  devise_for :users
  resources :clients do
    collection do
      get 'search'
      post 'import'
      get 'myClients'
    end
  end
  
  resources :users, only: [:index]

  resources :client_imports

  root 'clients#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :client, inverse_of: :notes
  #scope :by_client => client_id { where(:client_id => client_id) }

  def self.search(q)
    where("@client.id LIKE ?", "%#{client_id}%")
    where("user_id LIKE ?", "%#{user_id}%")
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
    @clientNotes = Note.where( client_id: params[:client_id]).all.order(id: :asc)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
    @client = Client.find(params[:client_id])
    @currentUser = User.find(current_user.id)
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note.client, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note.client }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note.client, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note.client }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:client_id, :user_id, :comment)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% if @note.new_record? %>
  <div class="field">
    <%= @client.name %>
    <%= f.hidden_field :client_id, :value => @client.id %>>
  </div>

  <div class="field">
    <%= @currentUser.username %>
    <%= f.hidden_field :user_id, :value => @currentUser.id %>>
  </div>
<% end %>
  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<% if params[:client_id] %>
<h2 align="center">Notes for <%= Client.where(id: params[:client_id]).first.name %> </h2>
<div class="container-fluid">
  <% @clientNotes.each do |t| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="client-name">
            <%= link_to(t.comment, note_path(t)) %>
            <% if t.user_id? %>
              <div class="client-user">
                <%= User.find(t.user_id).username %>
              </div>
            <% else %>
            <% end %>
          </div>
          <div class="client-address">
            <%= t.created_at %>
          </div>
          <div class="client-status">
            <%= t.updated_at %>
          </div>
          <div class="client-actions">
            <% if current_user.try(:admin?) %>
              <%= link_to("Edit", edit_note_path(t), class: "btn btn-xs btn-primary") %>
              <%= link_to("Delete", note_path(t), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-xs btn-danger") %>
            <% end %>
          </div>
        </div>
      </div>
  </div>
  <% end %>
</div>
<% end %>

<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.client %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @note.client.name %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>