config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :notes
  devise_for :users
  resources :clients do
    collection do
      get 'search'
      post 'import'
      get 'myClients'
    end
  end
  
  resources :users, only: [:index]

  resources :client_imports

  root 'clients#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  #attr_accessible :name, :address
  belongs_to :user
  has_many :notes, inverse_of: :client
  has_many :contacts, inverse_of: :client
  
  STATUSES = ['dnc', 'lead', 'open', 'client']
  TOPICS = ['Agriculture/Environment', 'Architecture', 'Arts & Culture', 'Business', 'Culinary', 'Education', 'Health/Medical', 'Outdoor', 'Travel']
  validates :address, uniqueness: { case_sensitive: false},
                      presence: true
  validates :status, inclusion: { :in => STATUSES,
                              message: "%{value} is not a valid type, please select either dnc, open or lead"}
  validates :category, inclusion: { :in => TOPICS,
                              message: "%{value} is not a valid Topic, please select from the list"}


  def self.category_filter(category)
    where("category LIKE ?", "%#{category}%")
  end
  
  def self.my_leads(userid)
    where(user_id: userid).where(status: 'lead')
  end

  def self.search(term)
    where("name ILIKE ? OR address ILIKE ?", "%#{term}%", "%#{term}%")
  end

  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      client = find_by_address(row["address"]) || new
      client.attributes = row.to_hash #.slice(*accessible_attributes)
      client.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
      when ".csv" then Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
      end



end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :search, :new, :create]
  before_action :set_client_user, only: [:show, :edit]
  before_action :check_admin, only: [:destroy, :import]
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all.order('LOWER(name)').includes(:user)
    if params[:q]
      @term = "#{params[:q]}"
      @clients = @clients.search(params[:q])
    elsif params[:user_id]
      @clients = @clients.my_leads(params[:user_id])
    elsif params[:category]
      @clients = @clients.category_filter(params[:category])
    end
  end

  def myClients
    @myClients = Client.where(user_id: current_user.id).all
    @myClients = @myClients.where(status: 'open').all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @notes = @client.notes.all
    @contacts = @client.contacts.all
  end

  def search
    @clients = Client.all
    respond_to do |format|
      format.html
      format.json { @clients = Client.search(params[:w]) }
    end
  end

  # GET /clients/new
  def new
    @client = Client.new
    @clientOwner = User.find(current_user.id)
  end

  # GET /clients/1/edit
  def edit
    if @client.user_id?
      @clientOwner = User.find(@client.user_id)
      else
      @clientOwner = current_user
    end
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)
    #@client.user_id = @clientOwner

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Client.import(params[:file])
    redirect_to clients_path, notice: "Companies imported"
  end

  private
  
    def check_admin
      @checkAcct = current_user
      @checkAcct.admin? == true
    end

    #def current_username
     # @currentUsername = current_user.username
    #end

    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    def set_client_user
      if @client.user_id?
        @clientOwner = User.find(@client.user_id)
        else
        @clientOwner = current_user
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :address, :status, :user_id, :category, :main_phone, :email_domain, :revenue)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_betashow.html.erb
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-6">
            <h3 class="center">Company Information</h3>
            <div class="panel panel-primary">
                <div class="panel-heading status-<%= @client.status %>">
                    <div class="client-name">
                        <%= @client.name %>
                    </div>
                        <strong>User:</strong>
                        <% if @client.user_id? %>
                          <%= @clientOwner.username %>
                        <% else %>
                          <strong>No user associated</strong>
                        <% end %>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-6">
                            <ul>
                                <li><strong>Topic: </strong><%= @client.category %></li>
                                <li><strong>Website: </strong><%= @client.address %></li>
                                <br><hr>
                                <li><strong>Updated: </strong><%= @client.updated_at.strftime('%H:%M:%S %B, %d, %Y') %></li>
                            </ul>
                        </div>
                        <div class="col-xs-6">
                            <ul>
                                <li><strong>Revenue: $</strong><%= @client.revenue %>M</li>
                                <li><strong>Main #: </strong><%= number_to_phone(@client.main_phone) %></li>
                                <li><strong>Email Domain: </strong><%= @client.email_domain %></li>
                                <hr>
                                <% if @client.notes.any? %>
                                    <li><strong>Last call: </strong><%= @client.notes.last.created_at.strftime('%H:%M:%S %B, %d, %Y') %></li>
                                <% end %>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="panel-footer">
                    <% if current_user.try(:admin?) or current_user.try(:beta?) %>
                      <%= link_to("Edit", edit_client_path(@client), class: "btn btn-xs btn-primary") %>
                      <%= link_to("Delete", client_path(@client), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-xs btn-danger") %>
                    <% end %>
                </div>
            </div>
            <div class="notes">
                <div class="center">
                    <li class='btn btn-success btn-md'><%= link_to("Add Note", new_note_path(:client_id => @client.id)) %></li>
                </div>
                <% if @client.notes.any? %>
                    <%= render 'clientnotes' %>
                <% end %>
            </div>
        </div>
        <div class="col-xs-6">
            <% if @client.contacts.any? %>
                <%= render 'clientcontacts' %>
                <li class='btn btn-success btn-md'><%= link_to("Add Contact", new_contact_path(:client_id => @client.id)) %></li>
            <% else %>
                <div class="center"><li class='btn btn-success btn-md'><%= link_to("Add Contact", new_contact_path(:client_id => @client.id)) %></li></div>
            <% end %>
        </div>
    </div>
</div>

app/views/clients/_clientcontacts.html.erb
<h3 align="center">Contacts</strong></h3>
<!-- <div class="center"><li class='btn btn-success btn-md'><%= link_to("Add Contact", new_contact_path(:client_id => @client.id)) %></li></div> -->
<% @contacts.each do |contact| %>
    <div class="panel panel-primary">
        <div class="panel-heading">
            <strong><%= contact.first_name %> <%= contact.last_name %> - <%= contact.title %></strong>
        </div>
        <div class="panel-body">
            <div class="col-xs-10 col-offset-2">
                <ul>
                    <li>Phone: <%= contact.phone_number %> x<%= contact.phone_ext %></li>
                    <li>Email: <%= contact.email %></li>
                    <li>Cell: <%= contact.cell_number %></li>
                </ul>
            </div>
        </div>
        <div class="panel-footer">
            <%= link_to("Edit", edit_contact_path(contact), class: "btn btn-xs btn-primary") %>
            <%= link_to("Delete", contact_path(contact), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-xs btn-danger") %>
        </div>
    </div>
<% end %>

app/views/clients/_clientnotes.html.erb
<h3 align="center">Notes</strong> </h3>
<div class="container-fluid">
  <% @notes.reverse_each do |t| %>
     <div class="col-xs-12">
        <div class="panel panel-default">
          <div class="panel-heading">
            <strong>Note Created: </strong> <%= t.created_at.strftime('%H:%M:%S %B, %d, %Y') %>
          </div>
          <div class="panel-body">
            <%= t.comment %>
            <% if t.user_id? %>
              <div class="client-user">
                <%= User.find(t.user_id).username %>
              </div>
            <% else %>
            <% end %>
          </div>
          
          <div class="panel-footer">
            <% if current_user.try(:admin?) %>
              <%= link_to("Edit", edit_note_path(t), class: "btn btn-xs btn-primary") %>
              <%= link_to("Delete", note_path(t), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-xs btn-danger") %>
            <% elsif current_user.try(:beta?) %>
              <%= link_to("Edit", edit_note_path(t), class: "btn btn-xs btn-primary") %>
              <%= link_to("Delete", note_path(t), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-xs btn-danger") %>
            <% end %>
          </div>
        </div>
      </div>
  
  <% end %>
</div>

app/views/clients/_form.html.erb
<div class="container">
<%= form_for(@client, :html => {class: "form"}) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <% if current_user.try(:admin?) %>
      <%= f.collection_select :user_id, User.order(:username), :id, :username %>
    <% else %>
      <p>Username: <%= @clientOwner.username %></p>
      <%= f.hidden_field :user_id, :value => @clientOwner.id %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :status %><br>
    <%= f.collection_select :status, Client::STATUSES, :to_s, :to_s %>
  </div>
  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.collection_select :category, Client::TOPICS, :to_s, :to_s %>
  </div>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address, 'Web Address' %><br>
    <%= f.text_field :address, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :main_phone %><br>
    <%= f.text_field :main_phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email_domain %><br>
    <%= f.text_field :email_domain, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :revenue %><br>
    <%= f.text_field :revenue, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>
</div>

app/views/clients/_results.html.erb
<div class="container-fluid">
    <% if @clients.blank? %>
        <h2>No matches found for: <%= @term %></h2>
    <% else %>
        <% @clients.each do |t| %>
            <div class="row">
                <div class="col-xs-8 col-xs-offset-2">
                    <div class="panel panel-result">
                        <div class="panel-heading">
                            <%= link_to(t.name, client_path(t)) %> | 
                            <%= t.status %>
                        </div>
                        <div class="panel-body">
                            
                        </div>
                        <div class="panel-footer">
                            
                        </div>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/clients/_searches.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12">
      <div class="panel panel-primary center-block">
        <div class="panel-heading center-block"><strong class="center-search">Search by Company Name or Website</strong></div>
        <div class="panel-body center-block"> Type part of the company name or website <strong>without the www.</strong>
          <div class="form-inline center-block">
            <%= form_tag(clients_path, :method => "get", id: "search-form", :html => {class: "form"}) do %>
            <div class="form-group center-block">
              <%= text_field_tag :q, params[:q], placeholder: "Company Name or Website", class: "form-control" %>
            </div>
            <%= submit_tag "Search", class: 'btn btn-primary' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>

app/views/clients/_topicdropdown.html.erb
<div class="container-fluid">
    <div class="panel panel-primary">
        <div class="panel-heading"><strong>View Companies by Topic</strong></div>
        <div class="panel-body">
            <div class="row">
                <div class="center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Topics <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><%= link_to("Agriculture/Environment", clients_path(category: "Agriculture/Environment"))  %></li>
                            <li><%= link_to("Architecture", clients_path(category: "Architecture"))  %></li>
                            <li><%= link_to("Arts & Culture", clients_path(category: "Arts & Culture"))  %></li>
                            <li><%= link_to("Business", clients_path(category: "Business"))  %></li>
                            <li><%= link_to("Culinary", clients_path(category: "Culinary"))  %></li>
                            <li><%= link_to("Education", clients_path(category: "Education"))  %></li>
                            <li><%= link_to("Health/Medical", clients_path(category: "Health/Medical"))  %></li>
                            <li><%= link_to("Outdoor", clients_path(category: "Outdoor"))  %></li>
                            <li><%= link_to("Travel", clients_path(category: "Travel"))  %></li>
                        </ul>
                    </div>
                </div>
                <br>
            </div>
        </div>
    </div>
</div>

app/views/clients/_topics.html.erb
<div class="container-fluid">
    <div class="panel panel-primary">
      <div class="panel-heading">View Companies by Topic</div>
      <div class="panel-body">
        <div class="row">
          <div class="col-md-4">
            <button type="button" class='btn btn-default'><%= link_to("Agriculture/Environment", clients_path(category: "Agriculture/Environment"))  %></button>
          </div>
          <div class="col-md-4">
            <button type="button" class='btn btn-default'><%= link_to("Architecture", clients_path(category: "Architecture"))  %></button>
          </div>
          <div class="col-md-4">
            <button type="button" class='btn btn-default'><%= link_to("Arts & Culture", clients_path(category: "Arts & Culture"))  %></button>
          </div>
        </div>
        <br>
        <br>
        <div class="row">
          <div class="col-md-4">
            <button type="button" class='btn btn-default'><%= link_to("Business", clients_path(category: "Business"))  %></button>
          </div>
          <div class="col-md-4">
            <button type="button" class='btn btn-default'><%= link_to("Culinary", clients_path(category: "Culinary"))  %></button>
          </div>
          <div class="col-md-4">
            <button type="button" class='btn btn-default'><%= link_to("Education", clients_path(category: "Education"))  %></button>
          </div>
        </div>
        <br>
        <br>
        <div class="row">
          <div class="col-md-4">
            <button type="button" class='btn btn-default'><%= link_to("Health/Medical", clients_path(category: "Health/Medical"))  %></button>
          </div>
          <div class="col-md-4">
            <button type="button" class='btn btn-default'><%= link_to("Outdoor", clients_path(category: "Outdoor"))  %></button>
          </div>
          <div class="col-md-4">
            <button type="button" class='btn btn-default'><%= link_to("Travel", clients_path(category: "Travel"))  %></button>
          </div>
        </div>
        <br>
      </div>
    </div>
  </div>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<div class="center search">
  <p id="notice"><%= notice %></p>
  <% if current_user.email == "james@frontpageprofile.com" %>
    <h2>Hello JJ, we always knew you'd come crawling back</h2>
  <% end %>
  


<div class="row">
  <div class="col-xs-12 col-md-3">
    <%= render 'topicdropdown' %>
  </div>
  <div class="col-xs-12 col-md-9">
    <%= render 'searches' %>
  </div>
</div> 
<h2 align="center">Do Not Call Listed Companies</h2>
<div class-"container-fluid">
    <% @clients.each do |t| %>
    <div class="row">
        <div class="col-xs-12 col-lg-8 col-lg-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading status-<%= t.status %>" style="font-size: 140%;">
                    <strong><%= link_to(t.name, client_path(t)) %></strong>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-xs-6">
                            <ul class="list-group">
                                <li class="center-block"><strong>Category: <%= t.category %></strong></li>
                                <li class="center-block"><strong>Website: <%= link_to(t.address, "http://#{t.address}", :target => "_blank") %></strong></li>
                            </ul>
                        </div>
                        <div class="col-xs-6">
                            <ul class="list-group">
                                <li class="center-block"><strong>Status: <%= t.status %></strong></li>
                                <% if t.user_id? %>
                                    <li class="center-block"><strong>User: <%= t.user.username %></strong></li>
                                <% end %>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="panel-footer clearfix">
                    <div class="client-actions">
                      <% if current_user.try(:admin?) or current_user.try(:beta?) %>
                        <%= link_to("Edit", edit_client_path(t), class: "btn btn-xs btn-primary") %>
                        <%= link_to("Delete", client_path(t), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-xs btn-danger") %>
                      <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/clients/myClients.html.erb
<h2 align="center">Your Leads</h2>
<div class="container-fluid">
  <% @myClients.each do |t| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="client-name">
            <%= link_to(t.name, client_path(t)) %>
            <% if t.user_id? %>
              <div class="client-user">
                <%= User.find(t.user_id).username %>
              </div>
            <% else %>
            <% end %>
          </div>
          <div class="client-address">
            <%= t.address %>
          </div>
          <div class="client-status">
            <%= t.status %>
          </div>
          <div class="client-actions">
            <% if current_user.try(:admin?) %>
              <%= link_to("Edit", edit_client_path(t), class: "btn btn-xs btn-primary") %>
              <%= link_to("Delete", client_path(t), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-xs btn-danger") %>
            <% end %>
          </div>
        </div>
      </div>
  </div>
  <% end %>
</div>

app/views/clients/new.html.erb
<div class="center">
  <div class="container">
    <h1>New Client</h1>
  </div>

  <%= render 'form' %>
  <div class="container">
    <h2>Import Clients/Leads</h2>

    <p><%= link_to("Import Clients", new_client_import_path, class: 'btn btn-primary btn-lg') %></p>
    <%= link_to('Back', clients_path, class: 'btn btn-warning') %>
  </div>
</div>

app/views/clients/search.html.erb
  
  <section class="app-content">
    <div class="clients-search">
      <input type="text" id="clients-search-txt" autofocus>
      <div class="results" id="clients-search-results"></div>
    </div>
  </section>
  <script>
    $( function() {
    this._input = $('#clients-search-txt');
    this._initAutocomplete();
};

 
    _initAutocomplete: function() {
        this._input
            .autocomplete({
                source: '/clients/search',
                appendTo: '#clients-search-results',
                select: $.proxy(this._select, this)
            })
            .autocomplete('instance')._renderItem = $.proxy(this._render, this);
    },
    
    _render: function(ul, item) {
        var markup = [
            '<span class="name"> + item.name + </span>',
            '<span class="address"> + item.address + </span>'
        ];
        return $('<li>')
            .append(markup.join(''))
            .appendTo(ul);
    },
    
    _select: function(e, ui) {
        this._input.val(ui.item.name + ' - ' + ui.item.address);
        return false;
    }
} );
  </script>
 
 <div class="ui-widget">
  <label for="clients">Company: </label>
  <input id="clients-search-txt">
</div>
  
  <%= content_for :script do %>
    new app.Clients;
  <% end %>

<script>
  $( function() {
    var availableTags = [
      "ActionScript",
      "AppleScript",
      "Asp",
      "BASIC",
      "C",
      "C++",
      "Clojure",
      "COBOL",
      "ColdFusion",
      "Erlang",
      "Fortran",
      "Groovy",
      "Haskell",
      "Java",
      "JavaScript",
      "Lisp",
      "Perl",
      "PHP",
      "Python",
      "Ruby",
      "Scala",
      "Scheme"
    ];
    $( "#clients-search-txt" ).autocomplete({
      source: 'search'
    });
  } );
</script>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>
<% if current_user.try(:beta?) %>
  <%= render 'betashow' %>
<% else %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
          <div class="panel panel-primary">
            <div class="panel-heading">
            <div class="client-name">
              <%= @client.name %>
               <div class="client-user">
                <strong>User:</strong>
                <% if @client.user_id? %>
                  <%= @clientOwner.username %>
                <% else %>
                  <strong>No user associated</strong>
                <% end %>
              </div>
            </div>
            </div>
            <div class="panel-body">
              <div class="client-address">
                <strong>Web Address:</strong>
                 <%= @client.address %>
              </div>
              <div class="client-address">
                <strong>Uploaded:</strong>
                <%= @client.created_at %>
                <strong>Last Updated:</strong>
                <%= @client.updated_at %>
              </div>
              
              <% if current_user.try(:beta?) %>
                <% if @client.notes.any? %>
                  <div class="client-address">
                    <strong>Last call:</strong>
                     <%= @client.notes.last.created_at %>
                  </div>
                <% end %>
              <% end %>
              
            </div>
            <div class="panel-footer">
              <strong>Account Status:</strong>
               <%= @client.status %>
               <% if current_user.try(:admin?) %>
                <%= link_to("Edit", edit_client_path(@client), class: "btn btn-xs btn-primary") %>
                 <%= link_to("Delete", client_path(@client), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-xs btn-danger") %>
               <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
<% end %>