config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :notes
  devise_for :users
  resources :clients do
    collection do
      get 'search'
      post 'import'
      get 'myClients'
    end
  end
  
  resources :users, only: [:index]

  resources :client_imports

  root 'clients#index'

end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-10 col-md-offset-1">
      <footer class="footer">
        <small>
          Copyright &copy; <%= link_to("Brian Arpaio", "http://rpayo.com/thingsimfixing", :target => "_blank") %>
        </small>
        <nav>
          <ul>
            <% if current_user.try(:admin?) %>
              <li><%= link_to("Search", root_path) %></li>
              <li><%= link_to("All Companies", clients_path) %></li>
              <!-- <li><%= link_to("Add New Company", new_client_path) %></li> -->
            <% end %>
          </ul>
        </nav>
      </footer>
    </div>
  </div>
  
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Do Not Call List", root_path, class: "navbar-brand", id: "logo") %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle nav-button" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Resources <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">PR Sites</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="http://www.prweb.com" target="_blank">PR Web</a></li>
            <li><a href="http://www.prnewswire.com" target="_blank">PR Newswire</a></li>
            <li><a href="http://www.pr.com" target="_blank">PR.com</a></li>
            <li><a href="http://24-7pressrelease.com" target="_blank">24-7 Press Release</a></li>
            <li><a href="http://www.ereleases.com" target="_blank">E Releases</a></li>
            <li><a href="http://www.prlog.org" target="_blank">PR Log</a></li>
            <li role="separator" class="divider"></li>

          </ul>
        </li>
        <% if current_user.try(:admin?) %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to("Add Company", new_client_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to("Companies", clients_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to("Mass Import", new_client_import_path) %></li>
            <li><%= link_to("View Users", users_path) %></li>
          </ul>
        </li>
        <% end %>
        <% if current_user.try(:beta?) %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Beta <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li role="separator" class="divider"></li>
            <li><%= link_to("My Leads", clients_path(user_id: current_user.id))  %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to("Add Company", new_client_path) %></li>
            <li><%= link_to("Mass Import", new_client_import_path) %></li>
          </ul>
        </li>
        <% end %>
      </ul>

      
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="#">User ID: <%= current_user.id %></a></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if current_user.try(:admin?) %>
            <li><a href="#">You're an admin</a></li>
            <li><%= link_to "My Leads", clients_path(user_id: current_user.id) %></li>
            <% end %>
            <% if user_signed_in? %>
              <li><%= link_to("Change your password", edit_user_registration_path) %></li>
              <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
            <% else %>
              <li><%= link_to("Sign up",  new_user_registration_path) %></li>
              <li><%= link_to("Login", new_user_session_path) %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Do Not Call List</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <!--
  <link rel="stylesheet" href="/resources/demos/style.css">
  -->
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</head>
<body>
<%= render 'layouts/navigation' %>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-8 col-lg-offset-2">
      <%= yield %>
    </div>
  </div>
  
</div>
<%= render 'layouts/footer' %>
</body>
</html>